apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team05
  name: t05-api
  labels:
    app: t05-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t05-api
  template:
    metadata:
      labels:
        app: t05-api
    spec:
      containers:
      - name: t05-api
        image: fujam20/api
        ports:
        - containerPort: 5000
--- 
apiVersion: v1
kind: Service
metadata:
  name: t05-api
spec: 
  type: ClusterIP
  selector:
    app: t05-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
