apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team05
  name: t05-fakemicroservice
  labels:
    app: t05-fakemicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t05-fakemicroservice
  template:
    metadata:
      labels:
        app: t05-fakemicroservice
    spec:
      containers:
      - name: t05-fakemicroservice
        image: fujam20/fakemicroservice