apiVersion: v1
kind: ConfigMap
metadata:
  name: t05-fluentd-config
  namespace: team05
data:
  fluent.conf: |-
    ################################################################
    # This source gets all logs from local docker host
    @include pods-kind-fluent.conf
    #@include pods-fluent.conf
    #@include file-fluent.conf
    @include elastic-fluent.conf
  pods-kind-fluent.conf: |-
    <source>
      @type tail
      read_from_head true
      tag fakemicroservice.*
      path /var/log/containers/t05-fakemicroservice*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
        @type json
        time_key timestamp
        time_format %iso8601
      </parse>
    </source>
    <filter fakemicroservice.**>
      @type parser
      key_name log
      hash_value_field "log"
      reserve_data true
      <parse>
        @type json
      </parse> 
    </filter>
  elastic-fluent.conf: |-
    <match fakemicroservice.**>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 't05-elasticsearch'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      index_name fakemicroservice
    </match>