apiVersion: apps/v1
kind: Deployment
metadata:
  name: t05-data-puller
  labels:
    app: t05-data-puller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t05-data-puller
  template:
    metadata:
      labels:
        app: t05-data-puller
    spec:
      containers:
      - name: t05-data-puller
        image: gitlab.sdu.dk:5050/semester-project-e2021/team-05/template/data-puller 
        ports:
        - containerPort: 5000
        env:
        - name: DATASEARCH_DOMAIN
          value: http://t05-datasearch
        resources:
          limits:
              cpu: 150m
              memory: 100Mi
          requests:
              cpu: 50m
              memory: 50Mi
      imagePullSecrets:
      - name: sdugitlab
--- 
apiVersion: v1
kind: Service
metadata:
  name: service03
spec: 
  type: ClusterIP
  selector:
    app: t05-data-puller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
