apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: team05
  name: t05-data-puller
  labels:
    app: t05-data-puller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t05-data-puller
  template:
    metadata:
      labels:
        app: t05-data-puller
    spec:
      containers:
      - name: t05-data-puller
        image: gitlab.sdu.dk:5050/semester-project-e2021/team-05/template/data-puller 
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: sdugitlab