apiVersion: apps/v1
kind: Deployment
metadata:
  name: t05-fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t05-fluentd
  template:
    metadata:
      labels:
        app: t05-fluentd
    spec:
      containers:
      - image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        imagePullPolicy: IfNotPresent
        name: t05-fluentd
        ports:
        - containerPort: 24224
          protocol: TCP
        volumeMounts:
        - mountPath: /fluentd/etc
          name: config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: t05-fluentd-config
        name: config
      imagePullSecrets:
      - name: sdugitlab
---

kind: Service
apiVersion: v1
metadata:
  name: t05-fluentd
  labels:
    app: t05-fluentd
spec:
  selector:
    app: t05-fluentd
  ports:
  - port: 24224
    protocol: TCP
    targetPort: 24224