apiVersion: apps/v1
kind: Deployment
metadata:
  name: t05-kibana
  labels:
    app: t05-kibana
spec:
  selector:
    matchLabels:
      app: t05-kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: t05-kibana
    spec:
      containers:
      - name: t05-kibana
        image: kibana:7.14.2
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: "http://t05-elasticsearch.staging.svc.cluster.local:9200"
        - name: ELASTICSEARCH_HOSTS
          value: "t05-elasticsearch.staging.svc.cluster.local"
 
---
apiVersion: v1
kind: Service
metadata:
  name: development
spec:
  selector:
    app: t05-kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
     


